version: '3.6'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"

    networks:
      - judge_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - judge_network

  broker:
    build: broker
    depends_on:
      - activemq
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - judge_network
#
#  database:
#    build: database
#    depends_on:
#      - broker
#      - mongodb
#    networks:
#      - judge_network
#    environment:
#      - MONGODB_URI=mongodb://mongodb:27017/codehub
#
#  grader_python:
#    build: graderPython
#    depends_on:
#      - broker
#    environment:
#      - QM_SERVER_HOST=activemq
#      - QM_SERVER_PORT=61610
#      - GRADER_ID=grader_1
#    networks:
#      - judge_network
#
#  coding_assistant:
#    build: codingAssistant
#    depends_on:
#      - broker
#      - mongodb
#    environment:
#      - QM_SERVER_HOST=activemq
#      - QM_SERVER_PORT=61610
#      - CLIENT_ID=ai_client_1
#    networks:
#      - judge_network
#
#  client:
#    build: codejudge_ui
#    depends_on:
#      - broker
#    ports:
#      - "3000:3000"
#      - "80:80"
#    environment:
#      - BROKER_PORT=8080

networks:
  judge_network:
    driver: bridge